services:
  catalogue_service:
    image: postgres:15
    container_name: catalogue_db_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: catalogue_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password


  keycloak_service:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak_container
    ports:
      - 8082:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
    command: start-dev --import-realm
