spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/authentication_db
    username: auth_username
    password: auth_password
  flyway:
    schemas:
      - public
      - user_management
shop:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password