spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: user_user
    password: user_password
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/realms/shop
server:
  port: 8081
logging:
  level:
    sql: info