spring:
  security:
    user:
      name: catalogue_service_user
      password: '{noop}password'
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: user_user
    password: user_password
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info